### ISSUE TITLE
Checkpoint 1 ready for review

### ISSUE THREAD

**Issue by mollymccarthy03** [mollymccarthy03/indie-online-planner#1]
@pawaitemadisoncollege

**Comment by pawaitemadisoncollege** [comment]
Hi @mollymccarthy03! 

I am really looking forward the online planner development that you will be doing as part of this class! It's a cool idea.  I'm really curious to know if the online version will work as well for you as the paper version! 

**Problem statement** 

Does a good job clearly explaining the problem and the solution. 
 
- [ ] I wonder if it might be helpful to include a photo or two of your current paper planning system. I like to think of the readme.md as the home page for your repository - the first thing a prospective employer will see and some images can always make that readme stand out!  

- [ ] Later you can include a short video on the readme demonstrating your solution! 

**User stories w/ MVP stories identified** Your users stories clearly communicate what your application will do. Your MVP stories seem to include what's needed for the ent java project requirements like crud. 

- [ ]  I'm unsure if there will be multiple one to many relationships here- we'll need to review that as you design the database and consider how to include the right level of complexity to demonstrate your skills. 

- [ ] Thinking about a web service or api that could be used in your project, I think there are a number of possibilities to explore!  It can be fun to poke around https://rapidapi.com/hub to see what apis are available. Sometimes students find inspiration out there! Is there any info you'd want on your calendar that you could pull from other sources, such as public holidays? Maybe days that school is closed (scrape the college website using jSoup?!)? Or, have you thought about some type of reminder for overdue items, or an email sent each week to the user with that week's schedule? I don't know if those make sense - sometimes my bad ideas will inspire some of your good ideas! This might even be a good conversation to have in #indie-project. 

**Screens**

Clean and simple!

- [ ] I am not sure if all user stories are represented. For example, delete? edit? 

- [ ] Something to know is that we'll be using AWS cognito for sign up/sign in capability, so there are some screens that you may not have to worry about as they can be provided by Cognito itself.  We'll learn more about this in week 7.

**Project Plan** 

- [ ] Formatting needs a little touch up - when viewing in GitHub some week numbers are heading sized and others are not. Some consistency there would make it easier to user and review.  If you have't worked with markdown before, you can use any of the readme.mds in the demos or exercises or check out this guide: https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax

- [ ] This needs work. Next steps for you should be: 
 
1. Identify which user story you plan to work on each week or weeks.  
2. Chatgpt can be helpful brainstorming tasks if you are having trouble coming up with them. The more detailed you can be the better. What do you think about creating a task for each story to decide which jsp/s, controllers, entities, tables you'll need for that story?
3. Revising the plan could be a task on the plan itself (woah!)

**Reflection/Time log** 

Keep up with this!

- [ ] Document all time spent in class, not just time on your indie project. This helps us both evaluate what might need more or less time!

*********
Do reach a met level with check point 1, I am most concerned about the plan. Can you work to address the items I listed under the plan and respond here when it is ready for review. 

If you have any questions, please ask!

**Comment by mollymccarthy03** [comment]
@pawaitemadisoncollege Hello! Thank you for all the great feedback. I went ahead and changed the Project Plan based on what you said. I am still having a hard time looking ahead to week 10-14 since I haven't started coding my project yet, but I am working on that this week, so maybe I will add more to the plan this week.

**Comment by pawaitemadisoncollege** [comment]
Hi @mollymccarthy03! I understand having a hard time with the planning part - this might be the first time you are planning a project of this size. I am going to list some tasks  for two user stories to get you started. Put these on your plan. My hope is that as you add these, you'll think of more to add!  My source of inspiration for these is your list of user stories and the screens.

**Tasks for View Daily Assignment List**

1. Design the Assignment table.
2. Create the Assignment table.
3. Create a script to put assignments in the table for testing.
4. Create the Assignment entity.
5. Create an Assignment DAO.
6. Create a unit test that tests getting today's assignment list from the database.
7. Create jsp for viewing today's daily assignment list.
8. Create a controller for managing the request for a the daily assignment list.
9. Connect the pieces to actually view daily assignments on the jsp.

**Tasks for Add Assignment**

1. Update the Assignment DAO for inserting.
2. Update the unit test to add an assignment.
3. Create a jsp to add an assignment
4. Create a controller to manage adding an assignment.
5. Connect the pieces to actually add the assignment from the jsp so that it makes it all the way to the database.

I hope this helps you add to your plan so you have a good idea of what needs to be done! Looking forward to seeing the revision!

**Comment by mollymccarthy03** [comment]
Hey @pawaitemadisoncollege I updated my project plan with what you said. Thank you for giving me that example, it really helped.

**Comment by pawaitemadisoncollege** [comment]
Hi @mollymccarthy03 - I'm glad to hear the example was helpful.  As I looked through your plan, I noticed a user table/entity/dao/test isn't included - you'll need to have users on a table in order to associate a user with their tasks.  

I'll review the plan again as part of checkpoint 2, so be sure to continue adding tasks and moving them forward if they are not completed in the week currently planned. 

It looks like you've started working on hibernate in your project - looking forward to reviewing that work when it is ready!

**Checkpoint 1: met**
