### ISSUE TITLE
Checkpoint #2 Ready for Review

### ISSUE THREAD

**Issue by mollymccarthy03** [mollymccarthy03/indie-online-planner#7]
@pawaitemadisoncollege

**Comment by pawaitemadisoncollege** [comment]
Hi @mollymccarthy03 

**Database designed and created**

- [x] Add the current erd to your repo for easy review and future reference.  

**At least one DAO with full CRUD (create, read, update, delete) implemented with Hibernate** - met

**DAO is fully unit tested** 

- [x] refer to my week 5 feedback regarding fully testing the one-to-many relationship
- [x] refer to my week 5 feedback regarding the generic dao (best practice to eliminate duplicate code)

**Log4J is implemented (no System.out.printlns)**

- [x] There's at least one System.out.println in your project. 

**Project plan updated with completed tasks**

- [x]  With just over a week left, this would be a good time to plan out what you'll do each day from now until "project complete"

**CP 2: not yet** Add the erd and fix printlns and let me know when it's ready for another look!

**Comment by mollymccarthy03** [comment]
checkpoint 2, ready for review! @pawaitemadisoncollege
